# Remove old {XXX}_OUTPUT_PATH entries, and use CMAKE_{XXX}_OUTPUT_DIRECTORY instead
unset(LIBRARY_OUTPUT_PATH CACHE)
unset(EXECUTABLE_OUTPUT_PATH CACHE)

set(CMAKE_CONFIGURATION_TYPES "Release;Debug" CACHE STRING "" FORCE)

set(LIBRARY_PREFIX "lib")
set(SHARED_LIBRARY_SUFFIX ".so")
set(STATIC_LIBRARY_SUFFIX ".a")
set(EXE_SUFFIX "")
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(BUILD_WINDOWS 1)
  set(LIBRARY_PREFIX "")
  set(SHARED_LIBRARY_SUFFIX ".dll")
  set(STATIC_LIBRARY_SUFFIX ".lib")
  set(EXE_SUFFIX ".exe")
else()
  set(BUILD_WINDOWS 0)
  if("${CMAKE_BUILD_TYPE}" STREQUAL "")
    message("For non-MSVC builds, You *must* specify the CMAKE_BUILD_TYPE (Release or Debug)")
  endif()
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  set(BUILD_MAC 1)
  set(SHARED_LIBRARY_SUFFIX ".dylib")
else()
  set(BUILD_MAC 0)
endif()

if(NOT BUILD_WINDOWS AND NOT BUILD_MAC)
  set(BUILD_LINUX 1)
else()
  set(BUILD_LINUX 0)
endif()

if(NOT DEFINED BUILD_64_BIT)
  # conditional, gives the user power to set -DBUILD_64_BIT=0
  if(CMAKE_SIZEOF_VOID_P STREQUAL 4)
    set(BUILD_64_BIT 0)
  else()
    set(BUILD_64_BIT 1)
  endif()
endif()
